### PR TITLE
Update guide #15

### PR DESCRIPTION
**Pull request by reisfmb**
The removal of the https://github.com/enonic/guide-custom-selector/issues/11 was on purpose, since in my point of view it doesn't make much sense to teach that in a guide that is specifically about creating a custom selector, that is, this is not a required step at all.

If you think this is necessary, I can add it... but my opinion is that "customizing custom selector with guillotine" would be better as a different guide.

### CODE REVIEW

**Comment by sigdestad** [comment]
Bruno - I partly agree. But these things are closely related, and I have actually been working for quite some time to improve this guide further - but it has not been committed yet. Worrid that all these changes will cause a big merge confligt with my code? Was not aware you were planning to work on this?

**Comment by reisfmb** [comment]
> Bruno - I partly agree. But these things are closely related, and I have actually been working for quite some time to improve this guide further - but it has not been committed yet. Worrid that all these changes will cause a big merge confligt with my code? Was not aware you were planning to work on this?

Hey Thomas. Didn't know you were working on improving this too and that will probably cause conflicts with your changes!

Last week I took some time to help Persijn on the slides for Dev 201. I wrote things for services and custom selector. From Persijn's perspective, both writings were complete and would better fit a guide, but he'll adapt those writings to slides. Based on his perspective I talked to Alan to see if it'd make sense to improve guides, and he let me do it, and this is the reason for this PR.

**Comment by reisfmb** [comment]
> Also, really like what I see you have done - but not sure how to handle the conflicts this will likely introduce?

Maybe, when you are done with your improvements, you can open a PR and we can see if it makes sense to mix our guide improvement ideas?

**Comment by sigdestad** [comment]
I see. Will have to discuss how to solve this with Alan then.

**Comment by alansemenov** [comment]
I thought you were working on the NextJS guide @sigdestad, not this one? How are they related?

**Comment by alansemenov** [comment]
> They are not, but I have been working on this guide since Tolya made an update to it - including the Guillotine things.

Ok, if you make a PR then we can merge your and Bruno's changes together.

**Review by alansemenov — APPROVED** [review]

**Comment by alansemenov** [comment]
Great job, Bruno!

**Pull request merged**
